import {ElTableColumn, ElTable, ElTag, ElTabs , ElTabPane, ElAlert, ElMessageBox, ElCascader, ElSelect, ElOption, ElMessage, ElTree, ElForm, ElFormItem, ElButton, ElDialog, ElPagination,ElContainer, ElSwitch, ElHeader, ElAside, ElTooltip ,ElMain, ElMenu, ElMenuItem, ElSubmenu, ElBreadcrumb, ElBreadcrumbItem, ElCard, ElInput, ElCol, ElRow} from 'element-plus'

export default (app) => {
  app.use(ElButton)
  app.use(ElContainer)
  app.use(ElHeader)
  app.use(ElAside)
  app.use(ElMain)
  app.use(ElMenu)
  app.use(ElSubmenu)
  app.use(ElMenuItem)
  app.use(ElSubmenu)
  app.use(ElBreadcrumb)
  app.use(ElBreadcrumbItem)
  app.use(ElCard)
  app.use(ElInput)
  app.use(ElCol)
  app.use(ElRow)
  app.use(ElTable)
  app.use(ElTableColumn)
  app.use(ElSwitch)
  app.use(ElTooltip)
  app.use(ElPagination)
  app.use(ElDialog)
  app.use(ElForm)
  app.use(ElFormItem)
  app.use(ElMessage)
  app.use(ElMessageBox)
  app.use(ElTag)
  app.use(ElTree)
  app.use(ElSelect)
  app.use(ElOption)
  app.use(ElCascader)
  app.use(ElAlert)
  app.use(ElTabs)
  app.use(ElTabPane)
}
